# Generated by Django 2.2.5 on 2019-10-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20191002_1310'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='likes',
            name='one_like_per_user_and_post',
        ),
    ]
