# Generated by Django 3.1 on 2020-08-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created']},
        ),
    ]
