# Generated by Django 3.0.2 on 2020-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
