# Generated by Django 3.0.2 on 2020-01-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
